app = "erik-minesweeper"
primary_region = "arn"

[build]

[env]
  PORT = "8080"
  OAUTH_REDIRECT_BASE = "https://sweepwars.com"
  RANKED_DB = "/data/ranked.db"

[mounts]
  source = "minesweeper_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
