// "Combined puzzles" admin page (#/admin/combined-puzzles).
//
// Starting-cascade patterns composed at a shared seam, generated by scripts/combine-patterns.js
// into combined-puzzles.json and served by GET /api/combined-puzzles. Each is a real
// {rows,cols,mines,revealed} board, so we reuse the All-Puzzles card + Analyze modal verbatim
// (renderPuzzleListCard / openAnalyzeModal from Puzzles.js) — passing the combined analyze
// endpoint as the base so "Analyze" plays the board and shows the solver trace just like the pool.

function renderCombinedPuzzles() {
	var view = document.getElementById("combined_puzzles_view");
	if (!view) return;
	view.innerHTML = "";

	var title = document.createElement("h1");
	title.className = "section-page-title";
	title.textContent = "Combined puzzles";
	view.appendChild(title);

	var sub = document.createElement("p");
	sub.className = "section-page-sub";
	sub.textContent = "Two starting-cascade patterns composed into one board (script-generated, scripts/combine-patterns.js). Cards are real puzzles — click Analyze to play and see the solver's move trace. Rated by the hardest forced deduction; the research question is whether composing building blocks beats the ~cx-8 ceiling a single opening hits.";
	view.appendChild(sub);

	var statusP = document.createElement("p");
	statusP.id = "combined_puzzles_status";
	statusP.className = "puzzles-list-status";
	view.appendChild(statusP);

	fetch("/api/combined-puzzles").then(function(r) { return r.json(); }).then(function(data) {
		var puzzles = (data && data.puzzles) || [];
		var unsat = (data && data.unsatisfiable) || [];
		statusP.textContent = puzzles.length
			? (puzzles.length + " combined puzzles" + (data.generatedAt ? " · generated " + data.generatedAt.slice(0, 10) : ""))
			: "No combined puzzles — run scripts/combine-patterns.js to build combined-puzzles.json.";

		// Group cards by the script's `group` field, hardest first within each group.
		var groups = [];
		var byGroup = {};
		puzzles.forEach(function(p) {
			if (!byGroup[p.group]) { byGroup[p.group] = []; groups.push(p.group); }
			byGroup[p.group].push(p);
		});
		groups.forEach(function(g) {
			var h = document.createElement("h2");
			h.className = "section-page-subtitle";
			h.textContent = g;
			view.appendChild(h);
			var grid = document.createElement("div");
			grid.className = "puzzles-grid";
			byGroup[g].sort(function(a, b) { return (b.cspMaxComplexity || 0) - (a.cspMaxComplexity || 0); });
			byGroup[g].forEach(function(p) { grid.appendChild(renderPuzzleListCard(p, "/api/combined-puzzles")); });
			view.appendChild(grid);
		});

		// Combinations whose clue rings conflict at the seam (no consistent mine layout exists) —
		// a real finding, surfaced as a note since they can't be realised as a board.
		if (unsat.length) {
			var note = document.createElement("div");
			note.className = "combined-unsat-note";
			var nh = document.createElement("h2");
			nh.className = "section-page-subtitle";
			nh.textContent = "No consistent layout (patterns conflict at the seam)";
			note.appendChild(nh);
			var ul = document.createElement("ul");
			ul.className = "combined-unsat-list";
			unsat.forEach(function(u) {
				var li = document.createElement("li");
				li.textContent = u.label;
				ul.appendChild(li);
			});
			note.appendChild(ul);
			view.appendChild(note);
		}
	}).catch(function(e) {
		statusP.textContent = "Error: " + e.message;
	});
}
